### ISSUE TITLE
Why change handler on pg 44 from "handler.handler"

### ISSUE THREAD

**Issue by bartonhammond** [JustServerless/learnserverless-book#6]
to "create/handler.handler" - what's that about?  Can you provide clarification why the default value is not sufficient?

I see this:

> Furthermore we tell Serverless to bundle the create folder with all it’s dependencies by changing the handler

but I don't understand the statement.  What happens if the change is not made?

**Comment by pmuens** [comment]
With this in place we're using the "magic handler" support by serverless.

By default on function creation, the handler is just `'handler.handler` …. which means only the root of the ​function​ will be deployed…

If you want to include a parent folder, you need to change the the handler property to be `folder/handler.handler`, because now that the handler path is aware of the `folder` folder, anything in the same level in the file tree will be deployed as well (ie. `node_modules`).
